### ISSUE TITLE
Release Management - Versioning, Minified Version

### ISSUE THREAD

**Issue by lukasender** [willfarrell/angular-modernizr#6]
Hey :)

Right now, there seems to be an issue when installling this module via `bower`.
There is no way to specify a version (it'll resolve to `"*"`).
My work around is using a specific `git commit hash`, which isn't pretty fancy I think.

The other thing I'm missing is a pre-minimized version of e.g. `placeholder.js`

(Off-topic: I've seen that the last commit was quite a while ago (2013). Do you recommend to use another module?)

Thanks in advance for your help (and your recent work :))!

**Comment by willfarrell** [comment]
Looks like I never added tags to repo. I just added some in for you. If I recall correctly, bower was in the process of adding that functionality at the time.

pre-minified version: https://github.com/willfarrell/angular-modernizr/blob/master/src/scripts/placeholder.js

If you can find other that are more recent that work better, go for it. I won't take it personally. I suggest trying several, to see which works best for your use case.

Hope this helps.
